export const HOME = 'HOME';
export const LOST = 'LOST';
export const LOST_FORM ='LOST_FORM'
export const FOUND = 'FOUND';
export const FOUND_FORM ='FOUND_FORM'
export const SERVICES = 'SERVICES';
export const FAVORITES = 'FAVORITES';
export const ADD_NEW = 'ADD_NEW';
export const PROFILE = 'PROFILE';